---
abstract: 'an XS implementation of Safe::Isa'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.014, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Safe-Isa-XS
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Safe::Isa::XS:
    file: lib/Safe/Isa/XS.pm
    version: 0.000_02
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Safe-Isa-XS/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Safe-Isa-XS
  homepage: https://metacpan.org/release/Safe-Isa-XS
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-safe-isa-xs
version: 0.000_02
